//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYPHONG
    {
        public int MADK { get; set; }
        public string HOTEN_GV { get; set; }
        public string DIACHI_GV { get; set; }
        public string SDT_GV { get; set; }
        public Nullable<System.DateTime> NGAY_DKPH { get; set; }
        public Nullable<System.DateTime> NGAY_TRAPH { get; set; }
        public string PHONGCHIDINH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    }
}
