//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUNGCU_CNTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUNGCU_CNTP()
        {
            this.CHITIETPHIEUNHAP_KHOA = new HashSet<CHITIETPHIEUNHAP_KHOA>();
            this.PHIEUNHAP_KHOA = new HashSet<PHIEUNHAP_KHOA>();
        }
    
        public string MADC { get; set; }
        public string TENDC { get; set; }
        public Nullable<int> LUONGTON { get; set; }
        public Nullable<int> LUONGTHANHLY { get; set; }
        public string DVT { get; set; }
        public Nullable<int> GIOSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP_KHOA> CHITIETPHIEUNHAP_KHOA { get; set; }
        public virtual DUNGCU DUNGCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP_KHOA> PHIEUNHAP_KHOA { get; set; }
    }
}
