//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUNGCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUNGCU()
        {
            this.BANGGIAs = new HashSet<BANGGIA>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUTHANHLies = new HashSet<CHITIETPHIEUTHANHLY>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
            this.CT_PHIEUMUON = new HashSet<CT_PHIEUMUON>();
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
            this.LISTTHANHLies = new HashSet<LISTTHANHLY>();
            this.MUONDCs = new HashSet<MUONDC>();
            this.TRADCs = new HashSet<TRADC>();
            this.TTBTRAs = new HashSet<TTBTRA>();
        }
    
        public string MADC { get; set; }
        public string TENDC { get; set; }
        public Nullable<int> LUONGNHAP { get; set; }
        public Nullable<int> LUONGXUAT { get; set; }
        public Nullable<int> LUONGTON { get; set; }
        public Nullable<int> LUONGTHANHLY { get; set; }
        public string DVT { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> GIOSD { get; set; }
        public string HINHANH { get; set; }
        public string MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGGIA> BANGGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTHANHLY> CHITIETPHIEUTHANHLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual CT_DUNGCU CT_DUNGCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual DUNGCU_CNTP DUNGCU_CNTP { get; set; }
        public virtual DUTRUDUNGCU DUTRUDUNGCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTTHANHLY> LISTTHANHLies { get; set; }
        public virtual LOAITTB LOAITTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONDC> MUONDCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRADC> TRADCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTBTRA> TTBTRAs { get; set; }
    }
}
