//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOACHAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOACHAT()
        {
            this.BANGGIAs = new HashSet<BANGGIA>();
            this.CHITIETKIEMDUYETs = new HashSet<CHITIETKIEMDUYET>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUTHANHLies = new HashSet<CHITIETPHIEUTHANHLY>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
            this.CT_PHIEUMUON = new HashSet<CT_PHIEUMUON>();
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
            this.LISTTHANHLies = new HashSet<LISTTHANHLY>();
            this.MUONHCs = new HashSet<MUONHC>();
            this.TRAHCs = new HashSet<TRAHC>();
            this.TTBTRAs = new HashSet<TTBTRA>();
        }
    
        public string MAHC { get; set; }
        public string TENHC { get; set; }
        public Nullable<int> MALHC { get; set; }
        public Nullable<int> THONGSO { get; set; }
        public string CASNO { get; set; }
        public string DONVI { get; set; }
        public Nullable<int> LUONGNHAP { get; set; }
        public Nullable<int> LUONGXUAT { get; set; }
        public Nullable<int> LUONGTON { get; set; }
        public Nullable<int> LUONGTHANHLY { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public string HINHANH { get; set; }
        public string MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGGIA> BANGGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKIEMDUYET> CHITIETKIEMDUYETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTHANHLY> CHITIETPHIEUTHANHLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual CT_HOACHAT CT_HOACHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual DUTRUHOACHAT DUTRUHOACHAT { get; set; }
        public virtual HOACHAT_CNTP HOACHAT_CNTP { get; set; }
        public virtual LOAIHOACHAT LOAIHOACHAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTTHANHLY> LISTTHANHLies { get; set; }
        public virtual LOAITTB LOAITTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONHC> MUONHCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAHC> TRAHCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTBTRA> TTBTRAs { get; set; }
    }
}
