//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOANTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOANTRA()
        {
            this.TTBTRAs = new HashSet<TTBTRA>();
        }
    
        public int MAHT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public string NOIDUNG { get; set; }
        public string NGUOITRA { get; set; }
        public string TU { get; set; }
        public string DEN { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTBTRA> TTBTRAs { get; set; }
    }
}
