//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGLAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGLAB()
        {
            this.PHIEUXUATPHONGLABs = new HashSet<PHIEUXUATPHONGLAB>();
        }
    
        public int MAPHLAB { get; set; }
        public string SOPHONG { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<int> LOAIPHONG { get; set; }
        public Nullable<int> SUCCHUA { get; set; }
        public string DIADIEM { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> LABActive { get; set; }
    
        public virtual LOAIPHONGLAB LOAIPHONGLAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUATPHONGLAB> PHIEUXUATPHONGLABs { get; set; }
    }
}
