//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI_CNTP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIETBI_CNTP()
        {
            this.CHITIETPHIEUNHAP_KHOA = new HashSet<CHITIETPHIEUNHAP_KHOA>();
            this.PHIEUNHAP_KHOA = new HashSet<PHIEUNHAP_KHOA>();
        }
    
        public string MATB { get; set; }
        public string TENTB { get; set; }
        public string QUICACH { get; set; }
        public Nullable<int> SLTON { get; set; }
        public Nullable<int> SLTHANHLY { get; set; }
        public string SERIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP_KHOA> CHITIETPHIEUNHAP_KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP_KHOA> PHIEUNHAP_KHOA { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
