//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIETBI()
        {
            this.BANGGIAs = new HashSet<BANGGIA>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETPHIEUTHANHLies = new HashSet<CHITIETPHIEUTHANHLY>();
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
            this.CT_PHIEUMUON = new HashSet<CT_PHIEUMUON>();
            this.CT_PHIEUTRA = new HashSet<CT_PHIEUTRA>();
            this.LISTTHANHLies = new HashSet<LISTTHANHLY>();
            this.MUONTBs = new HashSet<MUONTB>();
            this.TRATBs = new HashSet<TRATB>();
            this.TTBTRAs = new HashSet<TTBTRA>();
        }
    
        public string MATB { get; set; }
        public string TENTB { get; set; }
        public string QUICACH { get; set; }
        public Nullable<int> SLBANDAU { get; set; }
        public Nullable<int> SLXUAT { get; set; }
        public Nullable<int> SLTON { get; set; }
        public Nullable<int> SLTHANHLY { get; set; }
        public Nullable<bool> TAPHUAN { get; set; }
        public string SERIAL { get; set; }
        public string HINHANH { get; set; }
        public string MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGGIA> BANGGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTHANHLY> CHITIETPHIEUTHANHLies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUMUON> CT_PHIEUMUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUTRA> CT_PHIEUTRA { get; set; }
        public virtual CT_THIETBI CT_THIETBI { get; set; }
        public virtual DUTRUTHIETBI DUTRUTHIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTTHANHLY> LISTTHANHLies { get; set; }
        public virtual LOAITTB LOAITTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONTB> MUONTBs { get; set; }
        public virtual THIETBI_CNTP THIETBI_CNTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRATB> TRATBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTBTRA> TTBTRAs { get; set; }
    }
}
