//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDPHONGLAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTBTRA
    {
        public int MAHT_id { get; set; }
        public string MAHC_id { get; set; }
        public string MATB_id { get; set; }
        public string MADC_id { get; set; }
        public Nullable<int> SOLUONGTRA { get; set; }
    
        public virtual DUNGCU DUNGCU { get; set; }
        public virtual HOACHAT HOACHAT { get; set; }
        public virtual HOANTRA HOANTRA { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
